name: HDNNP
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python==3.6.7
  - ase
  - chainer
  - matplotlib
  - mpi4py
  - numpy
  - pyyaml
  - scikit-learn
  - scipy
  - traitlets
  - pip:
    - chainermn
