name: HDNNP
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - matplotlib
  - pyyaml
  - scikit-learn
  - scikit-optimize
  - mpi4py
  - ase
  - phonopy
  - chainer
  - pip:
    - chainermn==1.3.1
